### ISSUE TITLE
Small typo in the documentation link

### ISSUE THREAD

**Issue by schroef** [nutti/Magic-UV#57]
The link to the documentation page has a small typo.
Current;
https://github.com/nutti/Magic-UV/wikil

needs to be ofcourse;
https://github.com/nutti/Magic-UV/wiki

**Comment by nutti** [comment]
@schroef 

thanks, but i didn't get where the small typo has.

can you tell me the location?

**Comment by schroef** [comment]
check the URL, there is a L at the end which results in a wrong URL when it opens. We see a 404 page.

See address bar

<img width="1436" alt="screen shot 2017-07-08 at 4 15 54 pm" src="https://user-images.githubusercontent.com/6923008/27988765-bf0917ee-63f8-11e7-85cf-715f90619c39.png">

See the wiki URL in the  __init__.py
<img width="735" alt="screen shot 2017-07-08 at 4 17 31 pm" src="https://user-images.githubusercontent.com/6923008/27988779-faf1f28a-63f8-11e7-9237-da00119c38a3.png">

**Comment by nutti** [comment]
@schroef 

Thank you!!

i fixed this issue, so this problem will be fixed in next release.

and..., there is already fixed version on 2.79 release repo now.
however, the link to wiki_url is also changed.
it will link to the add-on catalog.

please see below patch.

https://developer.blender.org/rBA16df27d62e6a0aa3d1450bc56f5d90fdd05cf4a4

anyway, thanks for your report. i will release version 4.4 asap.

**Comment by nutti** [comment]
fixed version is already in develop branch.

so i will close.
