### ISSUE TITLE
[REQ] Add addon update from addon panel

### ISSUE THREAD

**Issue by schroef** [nutti/Magic-UV#74]
I am amazed how archipack does the addon update. As this addon is update a lot, perhaps this feature will give the user much easier and faster method of updating the plugin

see [this](https://github.com/s-leger/archipack/search?utf8=%E2%9C%93&q=update&type=)

![screen shot 2018-01-15 at 1 59 04 pm](https://user-images.githubusercontent.com/6923008/34955774-50f33a74-f9fc-11e7-8495-9cc6d278d557.png)

**Comment by nutti** [comment]
@schroef 

Yes, I know this feature.
But this feature depends on the CGCookie tools.
And this feature requires us to make release after merging request.

So, I will add this feature with other method.

**Comment by schroef** [comment]
what do you mean it requeres CG cookie tools? From what i could see, i did a super fast code check. The addon checks for a gitHub address.

This means you can point this to a certain location. Isnt it normal that you make a release after merging request? You can also just point to the last version

**Comment by nutti** [comment]
yes, that feature only looks GitHub url.

but i must release at every patches if you want to get newest version.
it does not best to this add-ons.

instead, i will make a update button to get newest develop branch.
however i am not sure there is a feature to realize this behavior.

**Comment by nutti** [comment]
you seems to enough experience to make python script.

if you want to revise this add-on, you can send me patch from pull request page :)

https://github.com/nutti/Magic-UV/pulls

**Comment by nutti** [comment]
I tried the archipack method which uses the CGCookie's blender add-on updater.
https://github.com/CGCookie/blender-addon-updater

But I raise an error, so I will implement this with my way.
CGCookie's tool is suitable for Magic UV.

**Comment by schroef** [comment]
What do you mean by "raise error", what kind of error?

Ive been doing some editting in that addon as well. I can now use releases and use clean zipped files. This way the user wont get any of the other stuff from the repo inside the blender addon folder. This makes the download much faster and the blender addon folder is stuffed with items from the github repo.

**Comment by nutti** [comment]
When I try to update the add-on, the error which __init__ is not found is raised.

The test codes are in issue_74 branch now.
Could you check please?

**Comment by schroef** [comment]
SOrry, but what do you mean but "The test codes are in issue_74 branch now"?
issue_74 is this thread, i dont get what your trying to explain

**Comment by schroef** [comment]
Ahh i get it, you meant branch issue_74, ill check it and see if i udnerstand it.

**Comment by schroef** [comment]
I see this when i reload the addon, doesnt seem like an error to me. 

`reloading addon: uv_magic_uv 1519304454.0 1519302988.0 /Users/PromotieSpullen/Library/Application Support/Blender/2.78/scripts/addons/uv_magic_uv/__init__.py
module changed on disk: /Users/PromotieSpullen/Library/Application Support/Blender/2.78/scripts/addons/uv_magic_uv/__init__.py reloading...
Warning: This script was written Blender version 2.79.0 and might not function (correctly), though it is enabled`

Other than that i dont see errors concerning UV Magic. Im using BL 2.78c though

**Comment by schroef** [comment]
Ahh wait, when installing it a issue occurs i see. Ill get back on it

**Comment by nutti** [comment]
@schroef 

Thanks for checking.
Yes, I have a same issue if I click the installing button.
It seems that updater script is not working correctly for my script...

**Comment by nutti** [comment]
@schroef 

I think below code does not work correctly.
https://github.com/schroef/blender-addon-updater/blob/master/addon_updater.py#L777-L790

**Comment by schroef** [comment]
I did read something on windows machines, they would need 'uv_magic_uv_updater' folder manually added. See [this](https://github.com/CGCookie/blender-addon-updater/issues/30) thread.

Im running into a new issue, since this week. I see a ssl warning protocol. Tried looking into [this](https://github.com/CGCookie/blender-addon-updater/issues/39), but it a bit to much complicated for me. Ive added a issue there, hope they can find something. I was working perfect for me all the time. Then i tried checking your issue and my also my internet went down. Since then i doesnt work. But im not sure what is related to what. Ive got 2 version of this updater running, they all show the same with different gitHub repos. Tried looking if they changed something in the API, but cant find it.

**Comment by TheDuckCow** [comment]
Hey there, I'm the maintainer of the CGCookie updater repository. I'll take a look at the issues mentioned here (not sure if there are one or multiple or what yet), but to echo what @schroef has said - the updater code is not dependent or connected to anything else (ie not connected or dependent on CGCookie). In fact, it actually works with Github, Gitlab, and bitbucket repositories (and even custom/other private repos with some minor code changes) - it just points to the github/gitlab/bitbucket web API given information like repository and username.

**Comment by nutti** [comment]
@TheDuckCow @schroef 

Hi,

Thanks, for your great script. It is super convenient script for adding feature of add-on update.
My real problem is to raise issue when the add-on has deep directory which includes ```__init__.py```

So, I tried to revise your script in my environment and have already fixed to update the add-on which has more than 2 level directory. I sent PR to your repository. If you don't mind, please review it.

https://github.com/CGCookie/blender-addon-updater/pull/40

Thanks again for sharing great script.

**Comment by nutti** [comment]
@schroef 

I found that there is v1.05 release about add-on updater.
So I will add add-on updater before releasing Magic UV v5.2.

But, it fails to connect my GitHub repository.
Do you know about this issue?

<img width="601" alt="issue" src="https://user-images.githubusercontent.com/1463952/47294302-9d025d00-d647-11e8-96c0-42a1f6d50bb7.png">

**Comment by TheDuckCow** [comment]
Hey there, as per [this issue here](https://github.com/CGCookie/blender-addon-updater/issues/39), this issue is specific to users running blender (2.79 public release or earlier) on OSX macs. This is actually an issue relating to how *python* is built for that system (the SSL version) and a recent update by the GitHub site in terms of which SSL versions they allow access, and there is no way to fix it as it is a concious decision by github to disallow [SSL version X and below]. Note if you run blender 2.8 or a recent dev build of 2.7x, you would not receive this error. Windows and linux users are not affected.

The v1.0.5 update was actually due to address this issue, in the sense that it at least gives this updated UI message "connection rejected" to help the user at least be able to manually check, whereas before it would just indicate a generic error and not give the user any indication of what to do or what was wrong.

To test your configuration, try running from a recent dev build of blender 2.79 (which uses more up to date python SSL bindings on OSX), or test on linux or windows - you should find it works there. Let me know if you have any issues.

**Comment by nutti** [comment]
@TheDuckCow 

Thanks.
I confirm that your script is now worked in windows environment.

Add-on updater is now in develop branch.
Thanks for your help.
